import React from 'react';
import { Download, FileJson, FileText } from 'lucide-react';

export default function ReportExport({ reportData }) {
  if (!reportData) return null;

  const exportJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(reportData, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `codeguard_report_${reportData.repository_name || 'analysis'}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const exportMarkdown = () => {
    const findingsList = (reportData.findings || []).map((f, i) => (
      `### ${i + 1}. [${f.severity.toUpperCase()}] ${f.title}\n` +
      `- **Category**: ${f.category}\n` +
      `- **File**: \`${f.file}${f.line ? `:${f.line}` : ''}\`\n` +
      `- **Source**: ${f.source}\n` +
      `- **Debt Impact**: ${f.technical_debt_impact}/10\n` +
      `- **Description**: ${f.description}\n` +
      (f.evidence ? `\`\`\`python\n${f.evidence}\n\`\`\`\n` : '') +
      `- **Recommendation**: ${f.recommendation}\n` +
      (f.rag_source ? `- **RAG Reference**: ${f.rag_source}\n` : '')
    )).join('\n\n');

    const recsList = (reportData.recommendations || []).map(r => (
      `### Priority ${r.priority}: ${r.title} (${r.estimated_effort_hours}h)\n` +
      (r.rationale ? `${r.rationale}\n\n` : '') +
      (r.action_items || []).map(a => `- ${a}`).join('\n')
    )).join('\n\n');

    const mdContent = `# CodeGuard AI Review Report: ${reportData.repository_name || 'Repository'}
**Date**: ${new Date(reportData.created_at).toLocaleString()}
**Commit**: \`${reportData.commit_hash || 'HEAD'}\` | **Branch**: \`${reportData.branch}\`

## Executive Summary
${reportData.executive_summary}

## Scores Overview
- **Overall Health Score**: ${reportData.scores?.overall_health_score}/100
- **Technical Debt Score**: ${reportData.scores?.technical_debt_score}/100
- **Security Posture Score**: ${reportData.scores?.security_score}%
- **Code Quality Score**: ${reportData.scores?.quality_score}%
- **Bug Safety Score**: ${reportData.scores?.bugs_score}%
- **Estimated Remediation Effort**: ${reportData.scores?.debt_remediation_hours} developer hours

## Prioritized Remediation Roadmap
${recsList || 'No outstanding recommendations.'}

## Detailed Findings (${reportData.findings?.length || 0})
${findingsList || 'No issues detected.'}

---
*Generated by CodeGuard AI - Multi-Agent AI Code Review & Technical Debt Analyzer*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codeguard_report_${reportData.repository_name || 'analysis'}.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ display: 'flex', gap: '10px' }}>
      <button
        type="button"
        className="preset-chip"
        style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', padding: '6px 12px' }}
        onClick={exportMarkdown}
      >
        <FileText size={14} /> Export Markdown (.md)
      </button>

      <button
        type="button"
        className="preset-chip"
        style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', padding: '6px 12px' }}
        onClick={exportJSON}
      >
        <FileJson size={14} /> Export JSON (.json)
      </button>
    </div>
  );
}
